#LandingPageLocaters
AcceptCookies="//*[@class='light-button accept']"
HandleBannerImage="//*[@class='container handledbanner']/*/*"
Second_TileGrid="//*[@class='column col-md-6 col-sm-6']"
Five_TileGrid="//*[@class='col-3 column col-md-6 col-sm-6']"
InspiroiduLinkText="//*[@id='wcmContentWidget_2_1552_84472']/div[2]/div[8]/div/p/a/img"
Three_TileGrid="//*[@class='col-3 column col-md-4 col-sm-4']"
S_EtujaBanner="//*[@id='wcmContentWidget_2_1552_84472']/div[2]/div[12]/div/p/a/img"
SelaaKuvastoaBanner="//*[@id='wcmContentWidget_2_1552_84472']/div[2]/div[14]/div"
SuggestionSliders="//*[@class='catalogEntryRecommendationWidget recommended  iospot']"
SuggestionSliderProducts="//*[@class='img-responsive vertical-align-middle m-auto']"
Page_LinkNext="//*[@class='page-link next']"
CatagoryTiles="//*[@class='column col-md-3 col-xs-6 col-sm-3 col-6']/../*"
BrandTiles="//*[@id='wcmContentWidget_3_1552_20951']/div[4]/div/div/p"

CarouselInner="//*[@class='carousel-inner']"
SubCategories="//*[@class='category-item']"
Categories="(//*[contains(@class,'nav-item h-100 text-nowrap dropdown')])"
CategoriesMegamenu = "//*[@data-parent='departmentsMenu']"
BrandContent="//*[@class='col-md-3 col-sm-3 column col-6']"
ProductListGrid="//*[@class='grid_mode grid']"
CurrentProductList="//*[@class='product_listing_container']/*/*"
ProductName="//*[@class='product_name']"
FavProductIcon="//*[@class='font-icon font-icon-favorite font-icon-before font-icon-size-2x']"
ProductPrice="//*[(contains(@class,'price d-flex flex-column ') or (contains(@class,'d-lg-flex flex-lg-column' )))]/*[1]"
CountPLP="(//*[@class='form-control page-link paging-select no-custom-icon'])[1]/*"
hrefAtribute = "//descendant::*[@class='ribbonplaceholder']/.."

#FilterLocaters
FilterOfHinta="//*[@id='OfferPrice_EUR_Sokos']"
LowPriceInput="//*[@id='low_price_input']"
HighPriceInput="//*[@id='high_price_input']"
ApplyPriceFilter="//*[@id='price_range_go']"
ClearFilter="//*[@class='p-1 pr-3 invisible-borders text-decoration-none']"
ColorFilter="//*[@id='Väri']"
ColorOption="//*[@id='Väri']/descendant::*//*[@class='btn btn-outline-success facetbutton toggle ']"
ColorsAmount = "//*[@id='Väri']/descendant::*//*[@class='facetCountContainer']/*"
MoreOption="//*[@id='Väri']/descendant::*[contains(text(),'Näytä lisää')]"
FilterApply="//*[@class='js-check-facet-container facetSelectContainer flex-wrap position-absolute background-light border p-3 facet-container collapse show']/descendant::*[contains(text(),'Käytä')]"
